version: '3.9'

services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: ams
    ports:
      - "${DJANGO_PORT}:8000"
    command: "sh /entrypoint.sh"
    env_file:
     - ../.env
    depends_on:
     - postgres
    volumes:
      - ..:/app/

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    networks:
      - ams-network
    depends_on:
      - main-app