version: '3.9'

services:
  ams-back:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: ams-back
    command: "sh /entrypoint.sh"
    env_file:
     - ../.env
    ports:
      - "${DJANGO_PORT}:8000"
    depends_on:
     - postgres
    volumes:
      - ..:/app/
      - static_volume:/app/static
      - media_volume:/app/media


  nginx:
    image: nginx:latest
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - ams-back
      - ams-front
    ports:
      - "80:80"

volumes:
  static_volume:
  media_volume: